services:
  reccoom:
    deploy:
      update_config:
        order: start-first
    environment:
      SENTRY_TRACES_SAMPLE_RATE: "0.1"
    image: ghcr.io/maevsi/reccoom:0.20.1
  reccoom-consumer:
    deploy:
      update_config:
        order: start-first
    environment:
      SENTRY_TRACES_SAMPLE_RATE: "0.1"
    image: ghcr.io/maevsi/reccoom:0.20.1
  reccoom-migration:
    deploy:
      update_config:
        order: start-first
    environment:
      SENTRY_TRACES_SAMPLE_RATE: "0.1"
    image: ghcr.io/maevsi/reccoom:0.20.1
    volumes: (( prune ))
  reccoom-postgres:
    deploy:
      update_config:
        order: stop-first
