apiVersion: 1
contactPoints:
  - orgId: 1
    name: Discord
    receivers:
      - uid: aen6t8xrd6pkwb
        type: discord
        settings:
          message: |-
            {{ define "__alert_details" }}
            {{ range . }}
            ⏰ **Started At:** {{ .StartsAt }}{{ if ne .EndsAt.String "0001-01-01 00:00:00 +0000 UTC" }}
            🛑 **Ended At:** {{ .EndsAt }}{{ end }}

            📝 **Annotations**
            {{ range .Annotations.SortedPairs }}- `{{ .Name }}` = {{ .Value }}
            {{ end }}🏷️ **Labels**
            {{ range .Labels.SortedPairs }}- `{{ .Name }}` = {{ .Value }}
            {{ end }}{{ if .GeneratorURL }}
            🔗 [Alert rule]({{ .GeneratorURL }}){{ end }}{{ if .DashboardURL }}
            📊 [Dashboard]({{ .DashboardURL }}){{ end }}{{ if .PanelURL }}
            📈 [Panel]({{ .PanelURL }}){{ end }}{{ if .SilenceURL }}
            🔕 [Silence this alert]({{ .SilenceURL }}){{ end }}{{ end }}{{ end }}{{ define "default.message_custom" }}{{ if .Alerts.Firing }}## 🚨 **Firing Alerts**
            {{ template "__alert_details" .Alerts.Firing }}{{ end }}{{ if .Alerts.Resolved }}## ✅ **Resolved Alerts**
            {{ template "__alert_details" .Alerts.Resolved }}{{ end }}{{ end }}{{ template "default.message_custom" . }}

            <@&1377144332154572831>
          url: $__file{/run/secrets/grafana-discord-webhook}
          use_discord_username: false
        disableResolveMessage: false
