services:
  postgraphile:
    deploy:
      labels:
        - (( append ))
        - traefik.http.routers.postgraphile.middlewares=postgraphile-auth,postgraphile-cors
        - traefik.http.routers.postgraphile-secure.tls.certresolver=default
      update_config:
        order: start-first
    image: ghcr.io/maevsi/postgraphile:2.0.0-beta.1
