services:
  portainer:
    deploy:
      labels:
        - (( append ))
        - traefik.http.routers.portainer-secure.tls.certresolver=default
      placement:
        constraints:
          - (( append ))
          - node.labels.vibetype.storage == true
      update_config:
        order: stop-first
