services:
  grafana:
    deploy:
      labels:
        - (( append ))
        - traefik.http.routers.grafana-secure.tls.certresolver=default
      placement:
        constraints:
          - node.labels.vibetype.storage == true
      update_config:
        order: start-first
