apiVersion: 1

datasources:
  - access: proxy
    editable: true
    jsonData:
      host: gizmosql
      port: 31337
      useTLS: false
      username: gizmosql
    name: GizmoSQL
    secureJsonData:
      password: $__file{/run/secrets/gizmosql-password}
    type: gizmodata-gizmosql-datasource
