{
 "title": "KPIs",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Monthly active users",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT id)\nFROM\n  vibetype_private.account\nWHERE\n  last_activity >= NOW() - INTERVAL '30 days';\n"
    }
   ]
  },
  {
   "title": "Last user activity",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('month', last_activity) AS month,\r\n    COUNT(*) AS \"Active user count\"\r\nFROM \r\n    vibetype_private.account\r\nGROUP BY \r\n    DATE_TRUNC('month', last_activity)\r\nORDER BY \r\n    month;\r\n"
    }
   ]
  },
  {
   "title": "User count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT created_at as time, row_number() OVER (ORDER BY created_at) FROM vibetype_private.account"
    }
   ]
  },
  {
   "title": "Accounts",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM\n  vibetype_private.account;\n"
    }
   ]
  }
 ]
}