apiVersion: 1
groups:
    - orgId: 1
      name: Critical
      folder: Infrastructure
      interval: 10s
      rules:
        - uid: een6tmiec4ge8f
          title: Notifications pending
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PCC52D03280B7034C
              model:
                editorMode: code
                format: table
                intervalMs: 1000
                maxDataPoints: 43200
                rawQuery: true
                rawSql: SELECT COUNT(1) FROM vibetype_private.notification WHERE is_acknowledged IS NULL OR is_acknowledged IS FALSE
                refId: A
                sql:
                    columns:
                        - name: COUNT
                          parameters:
                            - name: is_acknowledged
                              type: functionParameter
                          type: function
                    groupBy:
                        - property:
                            type: string
                          type: groupBy
                    limit: 50
                table: vibetype_private.notification
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            summary: There are notifications which are not sent out, or at least not marked as acknowledged.
          labels: {}
          isPaused: false
          notification_settings:
            receiver: 'Discord'
