services:
  prometheus:
    deploy:
      labels:
        - (( append ))
        - traefik.http.routers.prometheus-secure.tls.certresolver=default
      placement:
        constraints:
          - node.labels.vibetype.storage == true
      update_config:
        order: stop-first
