services:
  jobber:
    deploy:
      placement:
        constraints:
          - node.labels.vibetype.storage == true
      update_config:
        order: stop-first
    environment:
      SENTRY_CRONS: ${SENTRY_CRONS}
    volumes:
      - (( append ))
      - postgres-backup-data:/backups/
