services:
  jobber:
    deploy:
      update_config:
        order: stop-first
    environment:
      SENTRY_CRONS: ${SENTRY_CRONS}
    volumes:
      - (( append ))
      - postgres-backup-data:/backups/
