services:
  minio:
    # You can access the s3 console at [minio.app.localhost](https://minio.app.localhost/).
    # You can access the s3 api service at [s3.app.localhost](https://s3.app.localhost/) if you want to access via cli from outside the stack.
    command: server /data --console-address ":9001"
    deploy:
      labels:
        - dargstack.profiles=upload
        - traefik.enable=true
        # Minio Console
        - traefik.http.routers.minio.entryPoints=web
        - traefik.http.routers.minio.middlewares=redirectscheme
        - traefik.http.routers.minio.rule=Host(`minio.${STACK_DOMAIN}`)
        - traefik.http.routers.minio.service=minio
        - traefik.http.routers.minio-secure.entryPoints=web-secure
        - traefik.http.routers.minio-secure.rule=Host(`minio.${STACK_DOMAIN}`)
        - traefik.http.routers.minio-secure.tls.options=mintls13@file
        - traefik.http.routers.minio-secure.service=minio
        - traefik.http.services.minio.loadbalancer.server.port=9001
        - traefik.http.services.minio.loadbalancer.passhostheader=true
        # Minio itself
        - traefik.http.routers.s3.entryPoints=web
        - traefik.http.routers.s3.middlewares=redirectscheme
        - traefik.http.routers.s3.rule=Host(`s3.${STACK_DOMAIN}`)
        - traefik.http.routers.s3.service=s3
        - traefik.http.routers.s3-secure.entryPoints=web-secure
        - traefik.http.routers.s3-secure.rule=Host(`s3.${STACK_DOMAIN}`)
        - traefik.http.routers.s3-secure.tls.options=mintls13@file
        - traefik.http.routers.s3-secure.service=s3
        - traefik.http.services.s3.loadbalancer.server.port=9000
        - traefik.http.services.s3.loadbalancer.passhostheader=true
    entrypoint: /patched-entrypoint.sh
    image: minio/minio
    volumes:
      - minio-data:/data
      - ./configurations/entrypoint.sh:/patched-entrypoint.sh
    environment:
      MINIO_ROOT_PASSWORD: s3password
      MINIO_ROOT_USER: s3user
volumes:
  minio-data:
    # The s3 server's data.
    {}
