services:
  debezium:
    deploy:
      placement:
        constraints:
          - node.labels.vibetype.storage == true
      update_config:
        order: stop-first
  debezium-postgres-connector:
    deploy:
      placement:
        constraints:
          - node.labels.vibetype.storage == true
      update_config:
        order: stop-first
