services:
  redpanda:
    deploy:
      update_config:
        order: stop-first
  redpanda-console:
    deploy:
      labels:
        - (( append ))
        # The ui has no login of its own, so both routers sit behind basic authentication.
        - traefik.http.routers.redpanda.middlewares=redpanda-console-auth
        - traefik.http.routers.redpanda-secure.middlewares=redpanda-console-auth
        - traefik.http.routers.redpanda-secure.tls.certresolver=default
      update_config:
        order: start-first
